#!/usr/bin/env node
// build-catalog.mjs - reads every shipped SKILL.md's live frontmatter and emits
// generated/skill-catalog.md: one row per skill plus a trigger-phrase collision
// matrix so overlapping wake/trigger phrases are visible at build time, not
// discovered by users. Deterministic; re-run every release.
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const skillsDir = join(root, "skills");
const outFile = join(root, "generated", "skill-catalog.md");

function frontmatter(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---/);
  if (!m) return {};
  const fm = {};
  for (const line of m[1].split("\n")) {
    const i = line.indexOf(":");
    if (i > 0) fm[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return fm;
}

// Pull quoted trigger phrases from a description (the "Use when you say ..." set).
function phrases(desc) {
  const out = new Set();
  const re = /"([^"]{2,60})"/g;
  let m;
  while ((m = re.exec(desc)) !== null) out.add(m[1].toLowerCase().trim());
  return out;
}

const skills = [];
for (const name of readdirSync(skillsDir).sort()) {
  const p = join(skillsDir, name, "SKILL.md");
  try {
    if (!statSync(p).isFile()) continue;
  } catch { continue; }
  const text = readFileSync(p, "utf8");
  const fm = frontmatter(text);
  skills.push({
    name: fm.name || name,
    dir: name,
    desc: fm.description || "",
    phrases: phrases(fm.description || ""),
  });
}

// Collision matrix: any exact quoted trigger phrase shared by 2+ skills.
const phraseOwners = new Map();
for (const s of skills)
  for (const ph of s.phrases) {
    if (!phraseOwners.has(ph)) phraseOwners.set(ph, []);
    phraseOwners.get(ph).push(s.name);
  }
const collisions = [...phraseOwners.entries()]
  .filter(([, owners]) => owners.length > 1)
  .sort((a, b) => a[0].localeCompare(b[0]));

let md = `# Werkforce skill catalog (generated)\n\n`;
md += `<!-- GENERATED by scripts/build-catalog.mjs from live SKILL.md frontmatter. Do not hand-edit; re-run each release. -->\n\n`;
md += `Generated: ${new Date().toISOString().slice(0, 10)} · Skills: ${skills.length}\n\n`;

md += `## Skills\n\n| Skill | Trigger phrases | Description (first line) |\n|---|---|---|\n`;
for (const s of skills) {
  const first = s.desc.split(/[.·-]/)[0].slice(0, 90).replace(/\|/g, "\\|");
  const ph = s.phrases.size ? `${s.phrases.size} quoted` : "—";
  md += `| \`${s.name}\` | ${ph} | ${first} |\n`;
}

md += `\n## Trigger-phrase collision matrix\n\n`;
if (collisions.length === 0) {
  md += `No exact quoted trigger phrase is claimed by more than one skill.\n`;
} else {
  md += `Phrases claimed by 2+ skills - disambiguate or accept the overlap knowingly.\n\n`;
  md += `| Trigger phrase | Skills claiming it |\n|---|---|\n`;
  for (const [ph, owners] of collisions)
    md += `| "${ph}" | ${owners.map((o) => `\`${o}\``).join(", ")} |\n`;
}

md += `\n## Summary\n\n`;
md += `- Skills catalogued: **${skills.length}**\n`;
md += `- Distinct quoted trigger phrases: **${phraseOwners.size}**\n`;
md += `- Colliding phrases (2+ owners): **${collisions.length}**\n`;

writeFileSync(outFile, md);
console.log(`Wrote ${outFile}: ${skills.length} skills, ${collisions.length} colliding trigger phrases.`);
